### ISSUE TITLE
Implement job proxy calling Sloan DSS data

### ISSUE THREAD

**Issue by rillian** [trillian/trillian#1]
One of our proposed test data sets is the Sloan Digital Sky Survey.

This project already has a public data api at http://api.sdss3.org/

We should make a job proxy which pulls scripts from the job server and runs them against the sdss3 api. This will be a small stand-alone test of resource contribution, help verify our API design, and facilitate sandbox experiments without worrying about back-end data management.

**Comment by trillian** [comment]
Closing outstanding issues.

**Comment by trillian** [comment]
Ha - I wrote that API. :) Sadly it was shut down after I left. It will be replaced.
