### ISSUE TITLE
Andres Root: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by andres-root** [trillian/trillian#10]
Hi,
My name is Andres, I'm a developer from Colombia. I like this project because first of all I like Astronomy, a lot, and I'd love to help in this field of science. I'm not Astronomer though, I'm a Software Engineer, and I study physics by my self on Internet.

Regarding to my knowledge I have a good background on Python and Linux and also I work with Docker, a tool that allow developers to deploy apps on linux containers, easy and fast. My focus is backend and that is what I want to help to.<p><br><blockquote>This issue was created by @tracke via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by demitri** [comment]
Welcome Andres, and thanks for volunteering! Python will be the primary platform for Trillian, though we are looking at Docker for deploying apps. In this case, an "app" will be Python code provided the user. (It doesn't have to strictly be Python, but that's where we’re starting.) I haven't used it before, so getting an idea of how it works and how it will interface with the data on each node would be a great first step. The latter is being worked on by @maxogden and @ywyw.

I would suggest starting by looking at the [Trillian home page](http://trillianverse.org) if you haven't already, and if you are really ambitious the paper we wrote describing the project: http://arxiv.org/abs/1402.5932. It's a bit long and you can skip over the highly technical parts, but there is a description of the software design and infrastructure we’re hoping to build.

**Comment by demitri** [comment]
Hi @andres-root! It's taken a little time, but we're ready to move things forward and get people plugged into Trillian. If you are still interested, please sign up for the Trillian mailing list (linked below). There is a detailed welcome message with details on where things are now and how to contribute. Hope you can join us!

https://groups.google.com/forum/#!forum/trillianverse

**Comment by trillian** [comment]
Closing outstanding issues.
