### ISSUE TITLE
Ben A. Morgan: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by BenMorganIO** [trillian/trillian#12]
Hey, I'd love to help out with this project!

My background is in Ruby on Rails with some Angular/Ember. I'm wondering if I could help build the API and connect it to the DB? Rails is fantastic at APIs and DBs :D<p><br><blockquote>This issue was created by @BenMorganIO via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by BenMorganIO** [comment]
Bump.

**Comment by demitri** [comment]
Hi Ben - thanks for your interest, and apologies for the late reply. We'd definitely love the help. My preference is that we use Python as much as possible, mainly for the reason that the astronomical community is strongly trending to Python now, which means that the potential user base that can contribute later will be pretty large. I don't know any astronomer who knows Ruby, unfortunately. Do you have Python experience? On the JavaScript side, one of the tasks is to create a front end visualization for the data in Trillian - is that something you might be interested in working on?

**Comment by BenMorganIO** [comment]
0 python experience. For JavaScript, I'm :+1: for EmberJS.

**Comment by BenMorganIO** [comment]
Is there any python that doesn't require math/science code that I can help write? I wouldn't mind treading the python waters.

**Comment by demitri** [comment]
There is/will be. I'm in the process of trying to break up the large tasks that are in front of us into smaller ones, particularly ones that different people can tackle. I will have something shortly - it's kind of a hard problem.

**Comment by demitri** [comment]
Hi @BenMorganIO! It's taken a little time, but we're ready to move things forward and get people plugged into Trillian. If you are still interested, please sign up for the Trillian mailing list (linked below). There is a detailed welcome message with details on where things are now and how to contribute. Hope you can join us!

https://groups.google.com/forum/#!forum/trillianverse

**Comment by trillian** [comment]
Closing outstanding issues.
