### ISSUE TITLE
Serving raw images?

### ISSUE THREAD

**Issue by rainwoodman** [trillian/trillian#13]
I remember the plan is not serving raw images but mainly concentrate on the `final' survey products, like catalogues. 
Please correct me if I got this wrong. Thanks!

**Comment by demitri** [comment]
Trillian will need both. The catalog entries are essentially a list of numbers (position, magnitude, errors, etc.). However, one of the features is that models can return to the original pixels and calculate their own parameters from them. Some models will do this, some will not.

**Comment by trillian** [comment]
Closing outstanding issues.
