### ISSUE TITLE
WISE imaging data description

### ISSUE THREAD

**Issue by demitri** [trillian/trillian#14]
We need a simplified description of the released WISE imaging data. For a particular point on the sky, where does one get the corresponding image? What are the related files? Which ones do we need? What's the best way to index this without downloading them all? A place to start:

Format: http://wise2.ipac.caltech.edu/docs/release/allwise/expsup/sec4_1.html
File access: http://wise2.ipac.caltech.edu/docs/release/allwise/expsup/sec1_5.html
Cautionary notes: http://wise2.ipac.caltech.edu/docs/release/allwise/expsup/sec4_4.html  

There are 18,240 4095x4095 FITS image sets, one per Atlas Tile. More info in the links.

**Comment by rainwoodman** [comment]
Is this of interest?
https://astroquery.readthedocs.org/en/latest/irsa/irsa.html

**Comment by demitri** [comment]
Thanks for that. I'm familiar with Astropy (I’m an occasional contributor). I think the overhead of performing these calls is a lot higher compared to bulk downloading the source data and running it locally where applicable. There are cases where this won't be feasible, and looking into astroquery (which I haven't done in a while) is certainly a viable option.

That said, these are very thin wrappers around existing services and still focusses on implementation details. For example, that page describes access to IRSA, but that is a service, not a data set. What I want to do is:

```
from trillian.dataset import WISE
```

and access the data from there. Where it gets it from is irrelevant (to the user): it could be from our database, it could be from disk on Trillian, or it may trigger a query to IRSA. The point is that as a user I don't want to care.

There is a difference though between populating our database and using the data.

**Comment by trillian** [comment]
Closing outstanding issues.
