### ISSUE TITLE
Arun Kumar: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by palerdot** [trillian/trillian#15]
Hello Trillian, I'm a developer primarily working with Javascript who have interest in astronomy. I stumbled across this project and looks interesting to me. I would like to volunteer in any way I can. I noticed from this issue - https://github.com/trillian/trillian/issues/12 that you are looking to build some sort of visualization with Javascript for this project. I'm interested in knowing more about and see if I could be of any help in achieving that. Thanks and Regards.<p><br><blockquote>This issue was created by @palerdot via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by demitri** [comment]
Hi @palerdot! It's taken a little time, but we're ready to move things forward and get people plugged into Trillian. If you are still interested, please sign up for the Trillian mailing list (linked below). There is a detailed welcome message with details on where things are now and how to contribute. Hope you can join us!

https://groups.google.com/forum/#!forum/trillianverse

**Comment by trillian** [comment]
Closing outstanding issues.
