### ISSUE TITLE
Melissa Marshall: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by mveritym** [trillian/trillian#16]
Hi there, I'm a software developer and consultant living in San Francisco, CA. I have dual degrees in Computer Science and Physics (with an emphasis in astronomy). As an undergrad at Macalester College I built an IDL package for the automatic cleaning and analysis of dwarf galaxies imaged with Spitzer's IRAC. I also spent a summer at Caltech investigating image persistence in HdCdTe detectors, like the one aboard Hubble's WFC3. Although I've ended up software development and consulting, I think making astronomical data and analysis accessible to more people is one of the most interesting and meaningful problems out there. One of the things that frustrated me about academic astronomy research was the mismatch between astronomers' big ideas and their technical ability to execute them, particularly at smaller research institutions. I'm fairly new to the IT industry but I think I have a good foundation for helping to apply good software development practices and skills to the distributed analysis of astronomical data. Looking forward to working with you!<p><br><blockquote>This issue was created by @mveritym via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by demitri** [comment]
Hi @mveritym! It's taken a little time, but we're ready to move things forward and get people plugged into Trillian. If you are still interested, please sign up for the Trillian mailing list (linked below). There is a detailed welcome message with details on where things are now and how to contribute. Hope you can join us!

https://groups.google.com/forum/#!forum/trillianverse

**Comment by trillian** [comment]
Closing outstanding issues.
