### ISSUE TITLE
Investigate map-reduce as a compute script model

### ISSUE THREAD

**Issue by rillian** [trillian/trillian#7]
Our goal is to distribute compute jobs across large, multi-server datasets. It's unclear how best to expose this parallelism. One popular, easy to understand model is map-reduce.

Mock up an api for submitting jobs based on this model.

**Comment by rillian** [comment]
Extra points for modern techniques like referencing intermediate results by uuid.

**Comment by trillian** [comment]
Closing outstanding issues.
