### ISSUE TITLE
Hold a pipe (websocket?) open between job source and compute server

### ISSUE THREAD

**Issue by rillian** [trillian/trillian#8]
It should be possible to get logs or pass interactive commands from the job client as the job is running on the compute server. This allows a much better user experience and is important to design in early since it affects the basic architecture.

**Comment by rainwoodman** [comment]
It the pipe is routed through the job server, the job source do not need any direct access to the compute server. 

This can be more versatile if the compute server is behind a firewall etc.

**Comment by demitri** [comment]
I am considering using Redis as a job queue. This way if the network connection goes down, results/jobs can be queued and resume without a problem when the network is restored. At any rate, nodes will communicate with the central server either this way or through some kind of API, i.e. no direct access to the central database.

**Comment by trillian** [comment]
Closing outstanding issues.
